### ISSUE TITLE
Overview is hidden away after start up

### ISSUE THREAD

**Issue by solsticedhiver** [fthx/no-overview#1]
So, with the extension enabled, if I hit 'Super' key, to get the overview, it is hidden away automatically.
I have to hit 'Super' key a second time to get the overview as I expect it.

To fix this, I just disabled the extension....

**Comment by fthx** [comment]
Bonjour...

What version of GNOME do you use?

**Comment by solsticedhiver** [comment]
well, Gnome 40

**Comment by fthx** [comment]
And what OS?
I do use a Fedora 34 VM and I cannot reproduce (it never happens) the behavior you experience. No other user told me that it does not work as intended. And there are some users. So:
1) did you restart your session?
2) do you have some other extensions enabled?
Sorry to ask some simple questions, but experience told me that is not useless.

**Comment by solsticedhiver** [comment]
I am using archlinux.

The extension works as intended as it hides away automatically the overview at connection. But there is also a side effect I am reporting here.
It is that the overview in the session doe snot work well

Here is the list of the extensions I use:

[deleted]

**Comment by fthx** [comment]
Ok, I cannot handle all these possible interactions.
With only No Overview active, is the overview hidden at session start-up? After that, pressing Super key does show and hide the overview?
That's quite odd. This extension removes the signal linked to showing overview after its first use. So I really do not understand what's going on here.

**Comment by solsticedhiver** [comment]
It seems to be gone for now.

**Comment by mathieu-lemay** [comment]
It happens after a sleep. The signal gets re-activated so the first time you press `super`, the overview gets hidden and you need to press `super` again.

**Comment by fthx** [comment]
Thanks for the details. I look at this now.

**Comment by fthx** [comment]
(I cannot see all the bugs because I do not use GS 40, just test it through a VM.)

**Comment by fthx** [comment]
Ok:
https://github.com/fthx/no-overview/commit/025bbf357e7c90743f76ac21e75910b26dde8a9d

Feel free to reopen if needed.
It works when resuming from lock. I did not test that from sleep.

**Comment by mathieu-lemay** [comment]
Tested after resuming from both lock and sleep, works perfectly fine. Thank you very much!
