### ISSUE TITLE
Does this work with Ubuntu 22.04?

### ISSUE THREAD

**Issue by bronger** [fthx/no-overview#11]
Can anybody confirm that this extension works with Ubuntu 22.04? I cannot see any effect any more.

**Comment by fthx** [comment]
It does still work.
I do not use this extension (!!) but I do use Jammy and tested it a few min ago.

**Comment by mendhak** [comment]
It doesn't work for me for some reason, on 22.04.1 and Gnome Shell version is `GNOME Shell 42.5`

**Comment by mendhak** [comment]
Ah it was the Dash to Panel extension, it won't work with this one.  Instead, in the Dash to Panel settings there's an option to disable the overview.  Thanks.
