### ISSUE TITLE
Cannot leave overview & broken search box

### ISSUE THREAD

**Issue by pparik** [fthx/no-overview#12]
Thanks for this extension, however, there are two problems when the extension is enabled:

1. It is almost impossible to leave the overview via clicking on something or pressing SUPER. The only thing that works for me is clicking on Activities several times.
2. The first typed character in the overview is repeated several times in the search box (instead of once), or the typing is ignored.

Tested on Fedora 35, GNOME Shell 41.4 on Wayland.

**Comment by fthx** [comment]
Does this problem still occur?

**Comment by pparik** [comment]
> Does this problem still occur?

It seems it does not occur in GNOME Shell 41.8.1

**Comment by wiad** [comment]
This is still an issue on RHEL9 (gnome-shell-40.10-3.el9.x86_64)

**Comment by fthx** [comment]
Unfortunately I cannot test this in GS 40.
You could test with this extension (mine too, that has a no overview feature):
https://extensions.gnome.org/extension/5143/dashbar/
(not tested in GS 40 but should work)
Tell me if this issue happens too.

**Comment by bdwakefield** [comment]
Confirmed that this is happening for me:
Fedora 38
6.2.15-300.fc38.x86_64
GS 44.1

**Comment by fthx** [comment]
Does this problem still occur?
I mean, without any other extension installed.

**Comment by fthx** [comment]
Do you have Windows List extension installed?

**Comment by pparik** [comment]
The current version is even more unusable, it is not possible to click on any app when the overview is activated.
I only use Window List / Launch New Instance extensions.

I now use Fedora 38, GNOME shell 44.4 on X11.

**Comment by fthx** [comment]
And this bug is still here if no other extension is installed?

**Comment by pparik** [comment]
> And this bug is still here if no other extension is installed?

It seems to work when all other extensions are turned off (not uninstalled).

**Comment by fthx** [comment]
Ok so it's not compatible with Windows List, but I think this is not possible to bypass this.
