### ISSUE TITLE
simpler approach

### ISSUE THREAD

**Issue by icedman** [fthx/no-overview#2]
``js
/*
  License: GPL v3
*/

const Main = imports.ui.main;

class Extension {
    constructor() {
    }

    enable() {
        if (!Main.overview._runStartupAnimation) {
            Main.overview._runStartupAnimation = Main.overview.runStartupAnimation;
        }

        Main.overview.runStartupAnimation = (callback) => {
            callback();
        }
    }

    disable() {
        Main.overview.runStartupAnimation = Main.overview._runStartupAnimation;
    }
}

function init() {
	return new Extension();
}

``

**Comment by fthx** [comment]
Thanks for the proposal.

I tried it and I have two notes:
- there are silent errors (see logs, 'js' search, related to overview)
- I don't feel this approach to be simpler, that's just a (working!) hack like mine (+ addons by Florian)?

If you find a natural way to just disable the start-up overview (means without any modification of global functions/parameters), of course I'll take it with pleasure.
