### ISSUE TITLE
Kills GNOME Shell 44 when starting Ardour 7 with splash screen enabled

### ISSUE THREAD

**Issue by nphilipp** [fthx/no-overview#20]
SSIA, if the extension is enabled, when Ardour 7.2/7.3 would show its splash screen, GNOME Shell would crash. In the case of X11, the desktop session would restart with shell extensions disabled and a subsequent attempt would work. In the case of Wayland, you simply get logged out hard.

This happens with both Ardour 7 installed as an RPM package on Fedora 38, or the flatpak from flathub. A workaround is to start Ardour with the `-n` command line switch which suppresses the splash screen.

**Comment by fthx** [comment]
Sorry I have no idea about this and I don't use Ardour.

**Comment by liskin** [comment]
The splash screen of Skype for Linux set up to autostart triggers the crash as well.

**Comment by fthx** [comment]
Are there some errors in logs?

**Comment by liskin** [comment]
Don't remember seeing anything meaningful in there. ☹️ (It's my in-laws' computer, not a gnome user myself.)

**Comment by fthx** [comment]
Ok I close this, I cannot do anything here.
Seems to be a conflict between splash screen and the lack of overview at start-up.
My guess is that the overview comes with some init code that is triggered, after start-up if the ext is installed but needed for the splash screens.
