### ISSUE TITLE
New Mail Indicator Extension

### ISSUE THREAD

**Issue by ghost** [fthx/no-overview#26]
I know you're not maintaining it anymore, but please just update it to gnome 45, it is essential for my workflow, i need that for work, PLEASE!!!

**Comment by fthx** [comment]
You could have posted this in the right repo... ;-)
I updated new mail indicator, GS 45 version is coming.
Some cleanup (icon click actions, email client query).
Should be online soon.

**Comment by ghost** [comment]
The extension was marked as no longer maintained, and also the repo had a lot of issues not answered so i thought i had better chances in here.

Thank you for the update!
