### ISSUE TITLE
Versions are different between GitHub and Extensions.gnome

### ISSUE THREAD

**Issue by fujiwarat** [fthx/no-overview#27]
The GitHub provides the [version 45 Zip file](https://github.com/fthx/no-overview/archive/refs/tags/v45.zip) but The home page extensions.gnome.org provides the [version 15 Zip file](https://extensions.gnome.org/extension-data/no-overviewfthx.v15.shell-extension.zip).
I think it would be good to have the same version.

**Comment by fthx** [comment]
Here the versions are linked to GS version.
I cannot act on GS website versions.
