### ISSUE TITLE
Overview still showing in RHEL9.2 (gnome 40.10-12)

### ISSUE THREAD

**Issue by vtwaldo21** [fthx/no-overview#28]
I tried this plugin but the login overview still shows up.  I added some print statements and basically it just runs too late. The hasOverview flag is set to true by the sessionMode and sessionUpdated is called which pops the window, and then the extension is loaded and sets the overviewflag to false which appears to be too late as best as I can tell.

I tried calling _sync after setting the flag, but that just resets it back to true anyway. 

I don't know what controls the extension start order....

**Comment by vtwaldo21** [comment]
Ah, i got some more pertinent information. Turns out it didn't work when I also have just-perfect extension enabled. Disabling that extension and this extension works so the issue could be in that extension perhaps...

**Comment by vtwaldo21** [comment]
ok, sorry for the multiple posts.  I later learned that the issue is just-perfection also has the option to disable the overview as I guess the two methods clash.  So both work individually, pick the extension you want. THis issue can be closed.

**Comment by christopher-davidson** [comment]
I had just-perfection and no-overview working together in RHEL 9.3. Since upgrading to RHEL 9.4 (gnome-shell 40.10-17) the no-overview extension no longer works. Disabling just-perfection did not fix the issue with no-overview.
