### ISSUE TITLE
Gnome 45 

### ISSUE THREAD

**Issue by gautierlabarre** [fthx/no-overview#29]
Hello, I updated to gnome 45 and this extension doesn't work anymore?
I have uninstalled it and reinstalled but I still get the overview at startup. (I've restarted the computer of course)

What might I miss ? I've seen other threads where people say it works.

**Comment by fthx** [comment]
Hi,

I've just checked this using Ubuntu 23.10 and it works.

Could you tell me:
- distro
- exact GS version
- wayland or x11
- intel or nvidia or ?
- drivers (nvidia or nouveau)
- eGPU or dGPU
- monitors
- OTHER EXTENSIONS INSTALLED if any (please check this extension alone)
-

**Comment by gautierlabarre** [comment]
I disabled a few of my extensions and : 

The culprit is `dash to dock `which introduced a new parameter to do what your extension does. 
Don't know if this dash to dock option has been here for a while or not :) 
I don't have the issue now, your extension works :) 

I'll close the ticket. Thanks again

**Comment by anxest** [comment]
> I disabled a few of my extensions and :
> 
> The culprit is `dash to dock `which introduced a new parameter to do what your extension does. Don't know if this dash to dock option has been here for a while or not :) I don't have the issue now, your extension works :)

I have the same issue and also have Dash to dock installed, did you removed it completely or did you find a way to keep it without messing with the no-overview extension ?
I can't find a way to make those two work together without having the overview at startup :(

**Comment by gautierlabarre** [comment]
I removed this extension as Dash to dock does the same thing.
you have to go on dash to dock parameters, the 4th tab (appearance) and it's the second toggle to uncheck.
Sorry it's in french.
![image](https://github.com/fthx/no-overview/assets/13676992/3d7ed695-bc17-471e-a045-91b5b66ac4e7)
