### ISSUE TITLE
Request to use git tag to monitor source files with anitya

### ISSUE THREAD

**Issue by fujiwarat** [fthx/no-overview#3]
I'd like to monitor the version up in this project with [anitya project](https://release-monitoring.org/).

Unfortunately the extension home page is a little difficult to parse the version:
https://extensions.gnome.org/extension/4099/no-overview/

Probably I think it would help me if you could use `git tag` when you release the new ZIP file.
E.g. https://release-monitoring.org/project/13778/

**Comment by fthx** [comment]
Is it ok now?

**Comment by fujiwarat** [comment]
Thank you very much for the quick support.
I mapped the monitoring to Fedora now:
https://release-monitoring.org/project/212624/
