### ISSUE TITLE
Not working on GNOME 45

### ISSUE THREAD

**Issue by horga83** [fthx/no-overview#30]
Gnome always starts up in Overview mode even with app enabled. 
Running Arch Linux with latest updates and GNOME 45 on Wayland

Any clues?

**Comment by fthx** [comment]
Do you have any other extension?

**Comment by horga83** [comment]
I do but there seems no rhyme nor reason to which one it is.  I can
turn extensions off one by one and it works. Turn them on one at a time
and it stops working.  Go back and turn the last one off that caused it
to stop and it still doesn't work.  Turn a bunch off then try again and
same process.

I have no clear answer to which one it is and multiple extensions may
or may not cause it to stop working.  It's really very frustrating
trying to debug.  Sorry I couldn't give you a report that points to a
given extension.

I will say that I have no new extensions since Gnome 44 and it worked
fine then with all my current extensions enabled.  Of course we all
know that 45 really threw things for a loop so...

Thanks for your response.  If there is something I can do to help debug
please let me know.

Cheers
George

**Comment by fthx** [comment]
Maybe Dash to Dock?

**Comment by horga83** [comment]
I tried disabling Dash to Dock but it still happens.  Not sure how the
extensions work but do they load in some sort of priority?

**Comment by fthx** [comment]
Yes and we cannot know the order...
What are your extensions btw?

**Comment by horga83** [comment]
$ gnome-extensions list
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***

**Comment by fthx** [comment]
I just read stars for all of your extensions...

**Comment by fthx** [comment]
Well, we can continue but that's not a bug in this extension but a conflict with another.

**Comment by horga83** [comment]
Damn HTML mail anyway.  Try this:

$ gnome-extensions list
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***




On Wed, 2023-11-22 at 12:12 -0800, fthx wrote:
> Yes and we cannot know the order...
> What are your extensions btw?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>


-- 
George - VE7FRG

**Comment by horga83** [comment]
Yes, now how to go about finding which one, I have had no success, do
you have any tips for debugging this?

**Comment by fthx** [comment]
see Logs, search for JS.

**Comment by horga83** [comment]
Ok I know you closed this but here is the list once again, stupid
Github viewer.  Just in case you are interested.

gradienttopbar
dash-to-dock
caffeine
top-bar-organizer
Shortcuts
arch-update
Vitals
trayIconsReloaded
BringOutSubmenuOfPowerOffLogoutButton
ddterm
radio
systemd-manager
printers
apps-menu
auto-move-windows
places-menu
drive-menu
workspace-indicator
mediacontrols
quick-settings-audio-panel
system-monitor-next
no-overview
launch-new-instance
native-window-placement
screenshot-window-sizer
user-theme
window-list
windowsNavigator
Hide_Activities
light-style
gsconnect

**Comment by pantelm** [comment]
I had the same problem on manjaro, I disable all the extension except `no-overview` and then I enable all the extension and it work again.
I had the problem back after updating the `Freon` extension, I disable it, logged out, logged in and enable it, and `no-overview` work again

**Comment by fthx** [comment]
You can now try the new code (only in github atm). Tell me if it's ok now.

**Comment by horga83** [comment]
Unfortunately it behaves just as before, in other words for me it does
not work.  For reference I had "Just Perfection" installed to try and
it's show desktop does not work either, or more concisely it works
about 1% of the time.

I did uninstall Just Perfection to try yours and also did a clean
reboot, no go.

Thank you for trying.

**Comment by fthx** [comment]
Sorry but again, does new no-overview work without any other extension installed?

**Comment by horga83** [comment]
Same behaviour as before:

It works by itself, then I start enabling extensions and it quits when
I get to "Quick Settings Tweaker"
Disable "Quick Settings Tweaker" and it works but I can no longer
enable any other extension without it not working.

It's almost as if there is a limit to how many can be enabled and once
one goes over that number it doesn't work anymore.

I can randomly enable extensions and just adding one more cause no-
overview to not work

Quick Settings Tweaker is the 16th extension and after that it doesn't
work. 

So some times it's 15, sometimes it's 16 but certainly over that number
and it no longer works and that is randomly enabling extensions so it
doesn't seem to be tied to any one extension.

Cheers
George

**Comment by tomporter518** [comment]
Has any solution been found? I recently upgraded to Fedora 39 and now no-overview is very sporadic in operation. Some boots/logins, it works fine. Others the overview frame briefly changes size but the overview remains. I have two systems and they both behave similarly, in that no-overview doesn't function consistently.

**Comment by fthx** [comment]
You have to list your other extensions and the related errors ('js' or whatever) in gnome logs.
I do use Ubuntu with GS 45 and this extensions works 100 %.

**Comment by tomporter518** [comment]
I have restarted and relogged multiple times. There are no errors that I can discern from the journal. It feels like some sort of race condition, given the sporadic nature of not working. Though probably unrelated to this, a configured login sound also fails to play, seemingly because the audio subsystem isn't started/available yet. That makes me think 45 has different behavior on start up. If I log out and back in, after an initial login from a restart/reboot, I get more consistent behavior both on no-overview AND the login sound. My extensions are as follows:
``` 
hidetopbar@mathieu.bidon.ca
SettingsCenter@lauinger-clan.de
quick-settings-tweaks@qwreey
lockkeys@vaina.lt
openweather-extension@jenslody.de
sound-percentage@maestroschan.fr
dash-to-dock@micxgx.gmail.com
freon@UshakovVasilii_Github.yahoo.com
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
launch-new-instance@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
appindicatorsupport@rgcjonas.gmail.com
user-theme@gnome-shell-extensions.gcampax.github.com
caffeine@patapon.info
no-overview@fthx
drive-menu@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
```

**Comment by tomporter518** [comment]
The only mentions of any extension are these, though I don't know what they mean:
``` Jan 17 03:12:28 zane gnome-shell[2439]: Extension dash-to-dock@micxgx.gmail.com already installed in /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com. /usr/share/gnome-shell/extensions/dash-to-do>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension freon@UshakovVasilii_Github.yahoo.com already installed in /usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com. /usr/share/gnome-shell/exten>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. >
Jan 17 03:12:28 zane gnome-shell[2439]: Extension background-logo@fedorahosted.org already installed in /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org. /usr/share/gnome-shell/extensions/back>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.c>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.c>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension appindicatorsupport@rgcjonas.gmail.com already installed in /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com. /usr/share/gnome-shell/ext>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension caffeine@patapon.info already installed in /usr/share/gnome-shell/extensions/caffeine@patapon.info. /usr/share/gnome-shell/extensions/caffeine@patapon.info will>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension no-overview@fthx already installed in /usr/share/gnome-shell/extensions/no-overview@fthx. /usr/share/gnome-shell/extensions/no-overview@fthx will not be loaded
Jan 17 03:12:28 zane gnome-shell[2439]: Extension drive-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/drive-menu@gnome-shell-extensions.gcampax.github.com>
Jan 17 03:12:28 zane gnome-shell[2439]: Extension native-window-placement@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/native-window-placement@gnome-shell-ext>
```

**Comment by fthx** [comment]
Probably dash to dock, that does offer the no overview option.
Sorry but that's not due to No Overview.

**Comment by tomporter518** [comment]
Hmm...I guess I never knew that dash to dock had that feature. Sorry for the noise then since I probably don't need no-overview.

**Comment by fthx** [comment]
https://github.com/micheleg/dash-to-dock/blob/ac7e31749b1755a9d7abf8ff9a4471b2c8fb9f82/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml#L73

**Comment by horga83** [comment]
This would have been very useful information initially.  I had no idea
Dash to Dock had this option.  Once I disabled it no overview works as
it should.
