### ISSUE TITLE
Extension causes gnome-shell to freeze in overview

### ISSUE THREAD

**Issue by coralof** [fthx/no-overview#31]
Hello,

I noticed after enabling this extension, that after logging in (either from a fresh boot or logging out and back in), this extension causes gnome-shell to freeze when I enter overview mode (pressing the super key). 

With windows opened from the Applications menu, a few minutes after logging in:
![Screenshot from 2023-12-07 19-03-26](https://github.com/fthx/no-overview/assets/81376210/8d202abe-8424-447d-a773-053a20767a65)

No windows open, after a fresh login and hitting super:
![Screenshot from 2023-12-07 19-08-08](https://github.com/fthx/no-overview/assets/81376210/2fc03d85-0ed0-4cde-b92f-f325f5e44b77)

I did confirm that this extension caused it, by disabling it, logging out and back in and trying overview, and the freeze didn't occur. When I enabled it again and logged out and back in again, it froze again immediately upon hitting the super key (second photo). When it's frozen, the windows in overview will highlight when hovering over them to indicate they're the active window, but the only way to un-freeze it is to log out completely and back in again.

**OS**: Fedora 39
**GNOME**: 45.2
**Kernel**: 6.6.4-200.fc39.x86_64
**CPU**: 13th gen Intel Core i5-1340p
**Computer**: Framework 13

Thanks,
Cora

**Comment by fthx** [comment]
Do you see this issue with all other extensions disabled?
What extensions are you using?

**Comment by coralof** [comment]
Yes, I disabled every other extension except for **no-overview** (including system extension), logged out and back in, pressed super, and the issue still occurs.

**Comment by fthx** [comment]
Could you try with new code I've just uploaded?
https://github.com/fthx/no-overview/commit/c4d1546c271ff47d7cec9c4bca3b005d6bd715b1
You should briefly see the overview, though, and that's normal.

Please test this with screen lock and resume from sleep, too.

**Comment by coralof** [comment]
I just got home and swapped the new code in, and I can confirm that it works! I locked the screen and logged back in. Then logged out and back in, and finally restarted and logged back in, and can confirm that it works in each case now. Thank you so much!

**Comment by fthx** [comment]
Ok I will upload it on GS extensions website.
