### ISSUE TITLE
Imcompatible with gnome 46 for Fedora Rawhide 41

### ISSUE THREAD

**Issue by ghost** [fthx/no-overview#32]
![Screenshot from 2024-02-16 21-03-47](https://github.com/fthx/no-overview/assets/23100970/54dbd780-3bbc-4d8f-89a0-cd9f1763738c)

kamilcynk@fedora:~$ gnome-shell --version
GNOME Shell 46.alpha

kamilcynk@fedora:~$ cat /etc/redhat-release 
Fedora release 41 (Rawhide)

Could you kindly update extension for gnome 46 and push this to repository?

**Comment by fthx** [comment]
Uploaded, should be available soon.

**Comment by fujiwarat** [comment]
I think Fedora already provides the package.

**Comment by fujiwarat** [comment]
https://bodhi.fedoraproject.org/updates/?search=gnome-shell-extension-no-overview
