### ISSUE TITLE
The source files did not pass the integrity check!

### ISSUE THREAD

**Issue by ksawl** [fthx/no-overview#34]
I don't know what the cause is, but when I update I get this 
![Снимок экрана от 2024-04-06 16-19-06](https://github.com/fthx/no-overview/assets/1170589/822b0052-dde3-460e-a36b-e9358669f21e)

**Comment by akiirui** [comment]
Arch Linux Users? I have try to build this package [AUR/gnome-shell-extension-no-overview](https://aur.archlinux.org/packages/gnome-shell-extension-no-overview), it works fine.

Maybe you should remove cache? such `~/.cache/paru/clone/PKGNAME`

**Comment by fthx** [comment]
Hi all,

I've just pushed v46 that I did forgot to do.
I don't know if it can help Arch.

This issue is not related to the code here, please do that in AUR?
Thanks!
