### ISSUE TITLE
Fedora 41, extension not working

### ISSUE THREAD

**Issue by mantered** [fthx/no-overview#36]
The extension is not working in Fedora 41, Gnome 47.1 and extension version 18

**Comment by fujiwarat** [comment]
It works in Fedora 41. Did you install gnome-shell-extension-no-overview-47-1.fc41.noarch ?

**Comment by mantered** [comment]
It was installed from the "Extension manager" and it said Version 18 at the details page.
I had the same problem on desktop and laptop with Fedora 41.
Today after a fedora update the extension started to work, all good!
