### ISSUE TITLE
My gnome-shell 40.3 needed some changes for this extension to work...

### ISSUE THREAD

**Issue by Yaa101** [fthx/no-overview#4]
I had to change the following to make this extension work on Manjaro (Arch) with gnome-shell 40.3:

enable() {
--        if (!Main.layoutManager._startingUp) {
--          return;
--      }

Main.sessionMode.hasOverview = false;
++    Main.layoutManager.hideOverview();
        Main.layoutManager.connect('startup-complete', () => {
            Main.sessionMode.hasOverview = this._realHasOverview
        });
    }

Greetz...

**Comment by EvaristeGalois11** [comment]
Hi, can you elaborate a bit more on which errors you're receiving and what does this patch try to fix? I'm on Arch with gnome-shell 1:40.3-1 and everything works fine. I made an AUR for this extension so i'm interested if some patch needs to be applied for our distros. Could it be a downstream problem with Manjaro?

**Comment by fthx** [comment]
I did not get any other report for this, for any distro. For sure it would be the case if such an issue was reproducible, because there are many users.

Anyone feel free to reopen if confirmed!
