### ISSUE TITLE
when I press win button, I still found this overview

### ISSUE THREAD

**Issue by fanhang64** [fthx/no-overview#5]
Thx for your extension, it's very useful to me.
But I also found new problem. When I press the win button, I still found this overview. So I want to know how to solve this problem,thanks.

**Comment by EvaristeGalois11** [comment]
Hi, this extension is just for disabling the overview on start-up, it doesn't remove it completely. I'm afraid that if you don't want the overview tab showing up when pressing the win button the only solution is not pressing the button. You can't get rid of it as far as i know.

**Comment by fanhang64** [comment]
ok, I get it, thanks.
