### ISSUE TITLE
Not working on Ubuntu 21.10 Impish after recent update

### ISSUE THREAD

**Issue by olibax** [fthx/no-overview#8]
Neither this extension, nor the option on just perfection will prevent the overview mode upon sign-in. This issue only started after the recent update from Ubuntu.

**Comment by fthx** [comment]
What new GNOME subversion did break the extension?

**Comment by fthx** [comment]
Probably:
![image](https://user-images.githubusercontent.com/23138504/132206628-dd832856-4dbd-40d6-9618-9320c9b9bfcf.png)

**Comment by fthx** [comment]
If you do use the Ubuntu dock, this extension should now not be necessary.
Do you use it?

**Comment by tylerbax** [comment]
I'm not sure. It was within the last few days.
Here is my extension setup:
[image: Screenshot from 2021-09-06 07-46-19.png]
[image: Screenshot from 2021-09-06 07-46-41.png]

**Comment by olibax** [comment]
Interesting, after reading your comments I turned off dash to dock, your
extension, and enabled ubuntu dock. It now skips the overview at login.

**Comment by fthx** [comment]
Yes, as far as I read, Daniel Van Vugt created an option in GJS to skip overview at start-up. Then he pulled it in Dash to Dock.
