### ISSUE TITLE
Doesn't work with Ubuntu 21.10 Beta

### ISSUE THREAD

**Issue by chdslv** [fthx/no-overview#9]
Doesn't work with Ubuntu 21.10 daily, the overview continue to be there. This extension is on anyway.
By the way, it works on Fedora!

**Comment by diaevd** [comment]
Same

```bash
$ gnome-shell --version
GNOME Shell 40.5
```

```bash
$ echo $XDG_SESSION_TYPE 
wayland
````

**Comment by fthx** [comment]
Daniel Van Vugt from Ubuntu did hack GS allowing Dash to Dock to hide overview at start-up.
One line in 40.5-1ubuntu1 changelog.
So that's an Ubuntu bug. Note that I do use Impish.

If I remember correctly, DVV created a single gjs command to avoid overview at start-up. I'm open to a PR for Ubuntu.

**Comment by chdslv** [comment]
In Ubuntu Impish, this extension doesn't react at all, it is always with the overview. If there's a hide overview hack by DVV, by adding this extension broke that hack? Interestingly, with no hacks in Fedora 35, your extension works. I only added 41 to metadata.json.

**Comment by fthx** [comment]
Could you try the latest github code on Ubuntu+*Fedora*?
I found again:
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1943

**Comment by fthx** [comment]
Ok it works with Ubuntu 21.10 without errors.
Just have to try Fedora.

**Comment by fthx** [comment]
Could @fujiwarat check this too?
Thanks!

**Comment by fthx** [comment]
Please check the logs, of course!

**Comment by chdslv** [comment]
Yes, works with Impish and Fedora 35. Thanks!

**Comment by fthx** [comment]
I tested this in a Fedora 35 VM, it works too.

So I close this now. Feel free to reopen if needed.

I'm interested in knowing if just the "startInOverview" part is sufficent in Fedora 35. If you can test this?

**Comment by chdslv** [comment]
I am not good at coding, so all I can say is that, the old extension, and the new one works with Fedora 35. By the way, thank you very much for all your simple extensions. :)

**Comment by fthx** [comment]
Could you check the very latest github version?
I received an error report (without any detail) for Fedora **34** for the current version.

**Comment by fthx** [comment]
That's already online in GS ext website!

**Comment by chdslv** [comment]
I have Fedora 35, not 34. The versions 7, 8, 9 and 10 of your extension worked correctly with Fedora 35. In the version 7, I added 41 to metadata.json. 
In Impish, both version 9 and 10 works.

**Comment by ylxdzsw** [comment]
Not very related, but I just glanced at the code and find line 34 weird: we just set that variable to `false` in line 26, so I think it is always a no-op. Has anyone tested disabling the extension in Ubuntu?

**Comment by fthx** [comment]
I don't understand the point here. I just reenable the overview at start-up when disabling the extension.
Probably it's not useful as restarting the session does clear all that but anyway I find that's a good practice to let Gnome shell in a native state when disabling, assuming nobody does use this extension and Ubuntu dock at the same time.

**Comment by fthx** [comment]
If you ask about the "if" that's just to check if the variable does exist to avoid any error on systems without it (some non-Ubuntu GS 40, maybe outdated ones).

**Comment by ylxdzsw** [comment]
@fthx  Yes, but even if the variable exist, its value is "false", so the branch is still not entered.

**Comment by fthx** [comment]
Yes, maybe I should add || !Main.layoutManager.startInOverview ?
Or do nothing.

What do you think?

**Comment by fthx** [comment]
Additionally FYI, I don't check first the existence of Main.layoutManager.startInOverview before entering "old" hiding method.
Because as I experienced, the variable can exist BUT not be used by the system...

**Comment by ylxdzsw** [comment]
I'm no expert and don't use Ubuntu so can't say for sure. I think it would be fine to just set it even if it does not exist. Storing an additional (potentially unused) bool does not hurt anything, right?

**Comment by fthx** [comment]
https://github.com/fthx/no-overview/commit/857c68537c8b01b295d9df8599f27e8b7eaa2721

Thanks for pointing that.
